### ISSUE TITLE
error on "Server and Authentication" page

### ISSUE THREAD

**Issue by XPAction** [SEPIA-Framework/sepia-installation-and-setup#1]
I have installed sepia on a pi using the bundle.

when i try to login on the admin page, this error comes
```
{
  "msg": "Request was not sent! Plz check connection to server.",
  "info": {
    "readyState": 0,
    "status": 0,
    "statusText": "error"
  }
}
```

ive used this as login

```
UserID: admin@sepia.localhost
Client ID :

Custom server:
Select server: local-host-20721
```

Edit:
assist-v2.1.4
chat-1.1.0
teach-v2.0.2

**Comment by fquirin** [comment]
Hi,

sorry I just saw your post. For a faster reply please post here:
https://github.com/SEPIA-Framework/sepia-docs/issues

You said you've installed SEPIA on a Raspberry Pi. Are you trying to login from the same Pi or from any other device in your network?
Can you try to replace "localhost" with "raspberrypi.local" or the IP address of your Pi?

**Comment by XPAction** [comment]
Im trying to login from another device using "ipadress":20721/tools/index.html

**Comment by fquirin** [comment]
Oh I think I see the problem now. Since you did not specify a "custom server" the active server is "local-host-20721. Can you enter "ipadress":20721" in the "custom server" field and try again?
For v2.2.0 (just finished the test-build) I've done a lot of work on the tools page. It should be much more intuitive there ^^.

**Comment by XPAction** [comment]
ok now it says 
```
{
  "msg": "Request was not sent! Plz check connection to server.",
  "info": {
    "readyState": 0,
    "status": 0,
    "statusText": "SyntaxError: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL"
  }
}
```

Maybe I should try the new version

**Comment by XPAction** [comment]
Thanks, that was the problem.

**Comment by fquirin** [comment]
I'll close this issue, if you have further question feel free to post them here or even better: make a new issue at https://github.com/SEPIA-Framework/sepia-docs/issues (I'm trying to concentrate discussions there until SEPIA can afford it's own forum ^^).
