### ISSUE TITLE
Sepia Login failed! - Wrong username or password.

### ISSUE THREAD

**Issue by stevec1908** [SEPIA-Framework/sepia-installation-and-setup#10]
After setup, with no errors, i try to connect to the server:
http://192.168.0.197:20721/tools/index.html
But login form return:
Login failed! - Wrong username or password.
Same result trying http://192.168.0.197:20721/app/index.html. From console request URL is http://192.168.0.197:20721/authentication, answer is {"result":"fail","error":"400 or 500 bad request or communication error","code":"0"}.
What did I do wrong?

**Comment by sepia-assistant** [comment]
Hello,

Please post your questions here: https://github.com/SEPIA-Framework/sepia-docs/issues
It is the central place for all framework related issues.

What is the hostname you've entered on the login screen? Did you try to use the IP address only: "192.168.0.197" ?
