### ISSUE TITLE
polyfitting error 

### ISSUE THREAD

**Issue by Emere123** [SEPIA-Framework/sepia-installation-and-setup#30]
I have a question about the polyfitting 3D by the background removal. 
I am getting this erros:

Performing polynomial fitting...There was an error! Please check the command window/error message file for more information.
Output argument "b" (and maybe others) not assigned during call to "PolyFit".

Error in BackgroundRemovalMacro (line 103)
        [~,RDF,~]   = PolyFit(double(RDF),maskLocalFiled,refine_order);

Error in SepiaIOWrapper (line 264)
localField = BackgroundRemovalMacro(totalField,maskLocalfield,matrixSize,voxelSize,algorParam,headerAndExtraData);

Error in sepiaIO (line 78)
    SepiaIOWrapper(input,output,maskFullName,algorParam);

And I don't know how to fix it. My header and other steps before the background removal are working. But now the code says that my RDF is empty. 

Does somebody recognise my problem? Or have a solution for it?

**Comment by fquirin** [comment]
Hi @Emere123 are you sure this is the right project?
Honestly I have no idea what you are talking about :sweat_smile: , there is no 'BackgroundRemovalMacro' in any SEPIA code :thinking:
