### ISSUE TITLE
Try to install but error with Elasticsearch

### ISSUE THREAD

**Issue by sierdw84** [SEPIA-Framework/sepia-installation-and-setup#5]
Elasticsearch error:
Error occurred during initialization of VM
Server VM is only supported on ARMv7+ VFP

Running raspberry pi zero w, how can i change this so it will work?

**Comment by sierdw84** [comment]
Got it working:

Removed with purge all java and woldram,

and installed:
sudo apt-get install openjdk-8-jre-headless openjdk-8-jre
sudo apt-get install libpcre16-3
sudo apt-get install wolfram-engine

and changed to:
Xmx256M 
Xms256M

**Comment by fquirin** [comment]
:+1: was it a Java version issue? And is wolfram-engine really related to it? Haven't seen anything that ever mentioned it. Since the CPU is basically the same as in other RPi models I would expect no difference here.
